"""Add nome_empresa and status_publicacao fields

Revision ID: 002_add_nome_empresa_and_status
Revises: 16c6e459b36d
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_nome_empresa_and_status'
down_revision = '16c6e459b36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add nome_empresa column
    op.add_column('empreendimentos', sa.Column('nome_empresa', sa.String(length=255), nullable=True))
    
    # Add status_publicacao column
    op.add_column('empreendimentos', sa.Column('status_publicacao', sa.String(length=20), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE empreendimentos SET nome_empresa = nome WHERE nome_empresa IS NULL")
    op.execute("UPDATE empreendimentos SET status_publicacao = 'aguardando' WHERE status_publicacao IS NULL")
    
    # Note: SQLite doesn't support ALTER COLUMN to change nullable constraint
    # The nome_empresa field will remain nullable in SQLite, but the application will enforce it
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make construtora_id not nullable again
    op.alter_column('empreendimentos', 'construtora_id', nullable=False)
    
    # Remove added columns
    op.drop_column('empreendimentos', 'status_publicacao')
    op.drop_column('empreendimentos', 'nome_empresa')
    # ### end Alembic commands ###
