"""Sync database with current models

Revision ID: 16c6e459b36d
Revises: 001_initial_migration
Create Date: 2024-09-18 13:44:19.410057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '16c6e459b36d'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove table obras (not used in current models)
    op.drop_table('obras')

    # Add column observacao to empreendimentos
    op.add_column('empreendimentos', sa.Column('observacao', sa.Text(), nullable=True))

    # Remove old columns from empreendimentos
    op.drop_column('empreendimentos', 'cidade')
    op.drop_column('empreendimentos', 'estado')
    op.drop_column('empreendimentos', 'tipo')
    op.drop_column('empreendimentos', 'status')
    op.drop_column('empreendimentos', 'valor_total')
    op.drop_column('empreendimentos', 'unidades')

    # Add new columns to unidades
    op.add_column('unidades', sa.Column('tamanho_m2', sa.Float(), nullable=True))
    op.add_column('unidades', sa.Column('mecanismo_pagamento', sa.String(length=32), nullable=True, default='outros'))

    # Remove old columns from unidades
    op.drop_column('unidades', 'tipo')
    op.drop_column('unidades', 'area_m2')
    op.drop_column('unidades', 'quartos')
    op.drop_column('unidades', 'banheiros')
    op.drop_column('unidades', 'vagas_garagem')
    op.drop_column('unidades', 'status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Add back old columns to unidades
    op.add_column('unidades', sa.Column('status', sa.VARCHAR(length=50), nullable=True, default='Disponível'))
    op.add_column('unidades', sa.Column('vagas_garagem', sa.INTEGER(), nullable=True))
    op.add_column('unidades', sa.Column('banheiros', sa.INTEGER(), nullable=True))
    op.add_column('unidades', sa.Column('quartos', sa.INTEGER(), nullable=True))
    op.add_column('unidades', sa.Column('area_m2', sa.Float(), nullable=True))
    op.add_column('unidades', sa.Column('tipo', sa.VARCHAR(length=50), nullable=True))

    # Remove new columns from unidades
    op.drop_column('unidades', 'mecanismo_pagamento')
    op.drop_column('unidades', 'tamanho_m2')

    # Add back old columns to empreendimentos
    op.add_column('empreendimentos', sa.Column('unidades', sa.INTEGER(), nullable=True))
    op.add_column('empreendimentos', sa.Column('valor_total', sa.Float(), nullable=True))
    op.add_column('empreendimentos', sa.Column('status', sa.VARCHAR(length=50), nullable=True, default='Em planejamento'))
    op.add_column('empreendimentos', sa.Column('tipo', sa.VARCHAR(length=100), nullable=True))
    op.add_column('empreendimentos', sa.Column('estado', sa.VARCHAR(length=2), nullable=True))
    op.add_column('empreendimentos', sa.Column('cidade', sa.VARCHAR(length=100), nullable=True))

    # Remove new column from empreendimentos
    op.drop_column('empreendimentos', 'observacao')

    # Recreate obras table
    op.create_table('obras',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('nome', sa.VARCHAR(length=255), nullable=False),
        sa.Column('descricao', sa.TEXT(), nullable=True),
        sa.Column('empreendimento_id', sa.INTEGER(), nullable=True),
        sa.Column('status', sa.VARCHAR(length=50), nullable=True, default='Não iniciada'),
        sa.Column('data_inicio', sa.DATETIME(), nullable=True),
        sa.Column('data_fim_prevista', sa.DATETIME(), nullable=True),
        sa.Column('data_fim_real', sa.DATETIME(), nullable=True),
        sa.Column('valor_orcado', sa.Float(), nullable=True),
        sa.Column('valor_executado', sa.Float(), nullable=True),
        sa.Column('percentual_concluido', sa.Float(), nullable=True, default=0.0),
        sa.Column('publicado_em', sa.DATETIME(), nullable=True),
        sa.Column('expira_em', sa.DATETIME(), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True, default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.Column('updated_at', sa.DATETIME(), nullable=True, default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.ForeignKeyConstraint(['empreendimento_id'], ['empreendimentos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###
